### ISSUE TITLE
Access to the document within the fields option

### ISSUE THREAD

**Issue by serkandurusoy** [meteor-utilities/SmartQuery#1]
The filter option as access to both this.userId and the document but the fields option just has access to this.userId. It would be great if fields were up par with the filter option.

Building on the original readme example:

``` javascript
SmartQuery.addRule(Posts, {
  filter: function (document) {
    return document.published === true;
  },
  fields: function (document) {
    return this.userId === document.owner ? ["_id", "title", "body", "secretNotes"] : ["_id", "title", "body"]
  }
});
```

**Comment by SachaG** [comment]
I don't think that's actually possible? The fields specifier applies to the whole cursor, you can't have different fields for different documents in the same cursor. Unless I don't understand what you mean?

**Comment by serkandurusoy** [comment]
Ugh! The less the sleep the more the stupidty!

**Comment by SachaG** [comment]
Haha, it wasn't stupid… it took me a while to see why your suggestion didn't work, it wasn't that obvious :)
