### ISSUE TITLE
Could I use with "findOne()"?

### ISSUE THREAD

**Issue by thearabbit** [meteor-utilities/SmartQuery#2]
Could I use with "findOne()"?

**Comment by SachaG** [comment]
No, right now SmartQuery only supports `find`, not `findOne`. It needs some info from the cursor, so I don't think it would ever work from `findOne` since that only returns an array.

**Comment by thearabbit** [comment]
Thanks for your reply.

**Comment by thearabbit** [comment]
I would like to request this option.

**Comment by SachaG** [comment]
Sorry, that's not going to be possible. You have to use `find`, not `findOne`.
