### ISSUE TITLE
Could I use out of "template helper"?

### ISSUE THREAD

**Issue by thearabbit** [meteor-utilities/SmartQuery#3]
Could I use out of "template helper"?

``` js
Template.stats.events({
        'click .js-click': function (e, t) {
            var cursor = Posts.find({});
            alert(SmartQuery.create("posts2", cursor).count());
        }
    });
```
- click the fist time = 0
- click the second ... = 30

**Comment by SachaG** [comment]
Yeah you can use it anywhere. But it won't work in an event, since the subscription needs time to load the data, and the event is not a reactive context.

**Comment by thearabbit** [comment]
So I can check `isReady` to `alert()`.

**Comment by SachaG** [comment]
Well that's just not how Meteor (and JavaScript) works… Subscriptions are not synchronous, It's not really related to SmartQuery, sorry.

**Comment by thearabbit** [comment]
I tried

``` js
Template.stats.events({
        'click .js-click': function (e, t) {
            var cursor = Posts.find({});
            var query = SmartQuery.create("posts2", cursor);
            if (query.isReady()) {
                alert(query.count);
            }
        }
    });
```

But don't work

**Comment by thearabbit** [comment]
Could you example how to solve this?

**Comment by thearabbit** [comment]
Excuse me, I reopen this.

**Comment by SachaG** [comment]
You can't subscribe to something in an event and expect it to be available right away. You have to subscribe to it first, in the template's onCreated for example.
