### ISSUE TITLE
How to check is ready out of template helper?

### ISSUE THREAD

**Issue by thearabbit** [meteor-utilities/SmartQuery#4]
How to check is ready out of helper.

``` js
Template.stats.events({
        'click .js-click': function (e, t) {
            var cursor = Posts.find({});
            var query = SmartQuery.create("posts2", cursor);
            if (query.isReady()) {
                alert(query.count);
            }
        }
    });
```

Please help me how to solve?

**Comment by SachaG** [comment]
You just have to create the smartquery somewhere else.You can read up on how [reactivity](https://www.discovermeteor.com/blog/reactivity-basics-meteors-magic-demystified/) works to understand the issue here. 

Oh by the way, please don't create new issues for the same problem :)
